@host=http://localhost:5001
@token=YOUR_TOKEN

POST {host}/api/Products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "siteId": "00000000-0000-0000-0000-000000000000",
    "name": "string-name",
    "description": "string-description",
    "price": 0
}
